FROM registry.access.redhat.com/ubi8-minimal

ENV KEYCLOAK_VERSION 19.0.2
ENV JDBC_POSTGRES_VERSION 42.3.3
ENV JDBC_MYSQL_VERSION 8.0.22
ENV JDBC_MARIADB_VERSION 2.5.4
ENV JDBC_MSSQL_VERSION 10.2.1.jre11

ENV LAUNCH_JBOSS_IN_BACKGROUND 1
ENV PROXY_ADDRESS_FORWARDING false
ENV JBOSS_HOME /opt/jboss/keycloak
ENV LANG en_US.UTF-8

ARG GIT_REPO
ARG GIT_BRANCH
ARG KEYCLOAK_DIST=https://github.com/keycloak/keycloak/releases/download/$KEYCLOAK_VERSION/keycloak-legacy-$KEYCLOAK_VERSION.tar.gz

USER root

RUN microdnf update -y && microdnf install -y glibc-langpack-en gzip hostname java-11-openjdk-headless openssl tar which && microdnf clean all

ADD tools /opt/jboss/tools
RUN /opt/jboss/tools/build-keycloak.sh

USER 1000
#USER root
RUN rm -rf /opt/jboss/keycloak/modules/system/layers/base/org/apache/lucene/main/lucene-core-5.5.5.jar && \
    rm -rf /opt/jboss/keycloak/modules/system/layers/base/com/squareup/okhttp3/main/okhttp-3.14.9.jar && \
    rm -rf /opt/jboss/keycloak/modules/system/layers/base/org/yaml/snakeyaml/main/snakeyaml-1.29.jar && \
    rm -rf /opt/jboss/keycloak/modules/system/layers/base/org/yaml/snakeyaml/main/module.xml && \
    rm -rf /opt/jboss/keycloak/modules/system/layers/base/io/undertow/core/main/undertow-core-2.2.17.Final.jar && \
    rm -rf /opt/jboss/keycloak/modules/system/layers/base/io/undertow/core/main/module.xml && \
    rm -rf /opt/jboss/keycloak/modules/system/layers/base/org/jsoup/main/jsoup-1.14.2.jar && \
    rm -rf /opt/jboss/keycloak/modules/system/layers/base/org/jsoup/main/module.xml && \
    rm -rf /opt/jboss/keycloak/modules/system/layers/base/io/netty/netty-codec-http/main/netty-codec-http-4.1.76.Final.jar && \
    rm -rf /opt/jboss/keycloak/modules/system/layers/base/io/netty/netty-codec-http/main/module.xml && \
    rm -rf /opt/jboss/keycloak/modules/system/layers/base/org/apache/activemq/artemis/main/artemis-server-2.19.1.jar && \
    rm -rf /opt/jboss/keycloak/modules/system/layers/base/org/apache/xerces/main/xercesImpl-2.12.0.SP03.jar && \
    rm -rf /opt/jboss/keycloak/modules/system/layers/base/org/apache/xerces/main/module.xml && \
    rm -rf /opt/jboss/keycloak/themes/keycloak/common/resources/node_modules/select2 

COPY --chown=jboss:root newfilestemp/lucene-core-8.10.0.jar /opt/jboss/keycloak/modules/system/layers/base/org/apache/lucene/main/lucene-core-8.10.0.jar
COPY --chown=jboss:root newfilestemp/okhttp-4.9.2.jar /opt/jboss/keycloak/modules/system/layers/base/com/squareup/okhttp3/main/okhttp-4.9.2.jar
COPY --chown=jboss:root newfilestemp/snakeyaml-1.32.jar /opt/jboss/keycloak/modules/system/layers/base/org/yaml/snakeyaml/main/snakeyaml-1.32.jar
COPY --chown=jboss:root newfilestemp/module.xml /opt/jboss/keycloak/modules/system/layers/base/org/yaml/snakeyaml/main/module.xml
COPY --chown=jboss:root newfilestemp/undertow-core-2.2.19.Final.jar /opt/jboss/keycloak/modules/system/layers/base/io/undertow/core/main/undertow-core-2.2.19.Final.jar
COPY --chown=jboss:root newfilestemp/module_undertow.xml /opt/jboss/keycloak/modules/system/layers/base/io/undertow/core/main/module.xml
COPY --chown=jboss:root newfilestemp/jsoup-1.15.3.jar /opt/jboss/keycloak/modules/system/layers/base/org/jsoup/main/jsoup-1.15.3.jar
COPY --chown=jboss:root newfilestemp/module_jsoup.xml /opt/jboss/keycloak/modules/system/layers/base/org/jsoup/main/module.xml
COPY --chown=jboss:root newfilestemp/netty-codec-http-4.1.77.Final.jar /opt/jboss/keycloak/modules/system/layers/base/io/netty/netty-codec-http/main/netty-codec-http-4.1.77.Final.jar
COPY --chown=jboss:root newfilestemp/module_netty-code-http.xml /opt/jboss/keycloak/modules/system/layers/base/io/netty/netty-codec-http/main/module.xml
COPY --chown=jboss:root newfilestemp/artemis-server-2.24.0.jar /opt/jboss/keycloak/modules/system/layers/base/org/apache/activemq/artemis/main/artemis-server-2.24.0.jar
COPY --chown=jboss:root newfilestemp/xercesImpl-2.12.2.jar /opt/jboss/keycloak/modules/system/layers/base/org/apache/xerces/main/xercesImpl-2.12.2.jar
COPY --chown=jboss:root newfilestemp/module_xerces.xml /opt/jboss/keycloak/modules/system/layers/base/org/apache/xerces/main/module.xml
COPY --chown=jboss:root newfilestemp/select2/* /opt/jboss/keycloak/themes/keycloak/common/resources/node_modules/select2/

EXPOSE 8080
EXPOSE 8443

ENTRYPOINT [ "/opt/jboss/tools/docker-entrypoint.sh" ]

CMD ["-b", "0.0.0.0"]
